extends ESCItem

var _use_handcoded_event = false


# Example of how generate_events() might be implemented.
# This API is designed to be used when the implementation of
# ESCEvent is autogenerated from another tool. As this example
# illustrates, that tool might choose to implement the event
# by generating ESC script code, or it could also generate
# the GDScript code directly.
func generate_events() -> Dictionary:
	var exit_scene_event: ESCEvent
	if _use_handcoded_event:
		exit_scene_event = _load_event_coded_in_gdscript()
	else:
		exit_scene_event = _compile_event_from_esc()
	return {
		"exit_scene": exit_scene_event
	}


func _load_event_coded_in_gdscript() -> ESCEvent:
	var l_door_exit_scene = load("res://game/rooms/room03/l_door_exit_scene.gd")
	return l_door_exit_scene.new()


func _compile_event_from_esc() -> ESCEvent:
	var lines = [
		":exit_scene",
		"change_scene \"res://game/rooms/room02/room02.tscn\"",
	]
	var script = escoria.esc_compiler.compile(lines)
	return script.events["exit_scene"]
