class_name ESCTokenType


enum TokenType {
	INDENT, DEDENT, NEWLINE,

	COLON, COMMA, DOT, LEFT_PAREN, LEFT_SQUARE, RIGHT_PAREN, RIGHT_SQUARE,
	MINUS, PIPE, PLUS, QUESTION, SLASH, STAR,

	BANG, BANG_EQUAL,
	EQUAL, EQUAL_EQUAL,
	GREATER, GREATER_EQUAL,
	LESS, LESS_EQUAL,

	IDENTIFIER, STRING, NUMBER,

	AND, ELIF, ELSE, FALSE, IF, NIL, OR, PRINT, RETURN, TRUE, VAR, WHILE,

	EOF
}


static func get_token_type_name(type: int) -> String:
	return TokenType.keys()[type]
