class_name ESCTokenType


enum TokenType {
	INDENT, DEDENT, NEWLINE,

	COLON, COMMA, DOT, LEFT_PAREN, LEFT_SQUARE, RIGHT_PAREN, RIGHT_SQUARE,
	MINUS, PIPE, PLUS, SLASH, STAR,

	BANG, BANG_EQUAL, BANG_QUESTION,
	EQUAL, EQUAL_EQUAL,
	GREATER, GREATER_EQUAL,
	LESS, LESS_EQUAL,
	QUESTION, QUESTION_BANG,

	IDENTIFIER, STRING, NUMBER,

	AND, BREAK, DONE, ELIF, ELSE, FALSE, GLOBAL, IF, IN, INVENTORY, NIL, OR, PRINT, RETURN, TRUE, VAR, WHILE,

	EOF
}


static func get_token_type_name(type: int) -> String:
	return TokenType.keys()[type]
